config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :animals, only: [] do
    collection do
      get  :index
    end
  end

  resources :dogs, only: [] do
    collection do
      get  :index
    end
  end

  resources :cats, only: [] do
    collection do
      get  :index
    end
  end

  resources :dog_parents do
  end

  resources :dog_children, only: [] do
    member do
      get   :children
      get   :child_new
      post  :child_create
      get   :child_show
      get   :child_edit
      patch :child_update
    end
  end

  resources :cat_parents do
  end

  resources :cat_children, only: [] do
    member do
      get   :children
      get   :child_new
      post  :child_create
      get   :child_show
      get   :child_edit
      patch :child_update
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  use_switch_point :main
  SwitchPoint.writable!(:main)
end

app/models/application_record_another.rb
class ApplicationRecordAnother < ActiveRecord::Base
  self.abstract_class = true
  use_switch_point :another
  SwitchPoint.writable!(:another)
end

app/models/cat_child.rb
class CatChild < ApplicationRecordAnother
  belongs_to :cat_parent, required: false
end

app/models/cat_parent.rb
class CatParent < ApplicationRecordAnother
  has_many :cat_children
end

app/models/dog_child.rb
class DogChild < ApplicationRecord
  belongs_to :dog_parent, required: false

  after_create do
    if name == 'AFTER CREATE TEST'
      cat = CatChild.new
      cat.save!
    end
  end

  after_commit do
    if name == 'AFTER COMMIT TEST'
      cat = CatChild.new
      cat.save!
    end
  end
end

app/models/dog_parent.rb
class DogParent < ApplicationRecord
  has_many :dog_children
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    ApplicationRecord.with_readonly do
      @dog_parents_count = DogParent.all.size
    end
    ApplicationRecordAnother.with_readonly do
      @cat_parents = CatParent.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def with_readonly
    ApplicationRecord.with_readonly { yield }
  end

  def with_readonly_another
    ApplicationRecordAnother.with_readonly { yield }
  end
end

app/controllers/cat_children_controller.rb
class CatChildrenController < ApplicationController

  def children
    @cat_parent = CatParent.find(params[:id])
    @cat_children = @cat_parent.cat_children
  end

  def child_show
    @cat_child = CatChild.find(params[:id])
  end

  def child_new
    @cat_parent = CatParent.find(params[:id])
    @cat_child = CatChild.new
  end

  def child_create
    @cat_parent = CatParent.find(params[:id])
    @cat_child = @cat_parent.cat_children.build
    @cat_child.name = params.dig(:cat_child, :name)
    if @cat_child.save
      redirect_to children_cat_child_path(@cat_parent), notice: '作成しました'
    else
      render :child_new
    end
  end

  def child_show
    @cat_child = CatChild.find(params[:id])
  end

  def child_edit
    @cat_child = CatChild.find(params[:id])
  end

  def child_update
    @cat_child = CatChild.find(params[:id])
    @cat_child.name = params.dig(:cat_child, :name)
    if @cat_child.save
      redirect_to child_show_cat_child_path(@cat_child), notice: '保存しました'
    else
      render :child_edit
    end
  end
end

app/controllers/cat_parents_controller.rb
class CatParentsController < ApplicationController

  def index
  end

  def show
  end

  def new
    @cat_parent = CatParent.new
  end

  def create
    @cat_parent = CatParent.new
    @cat_parent.name = params.dig(:cat_parent, :name)
    if @cat_parent.save
      redirect_to cat_parents_path, notice: '作成しました'
    else
      render :new
    end
  end

  def show
    @cat_parent = CatParent.find(params[:id])
  end

  def edit
    @cat_parent = CatParent.find(params[:id])
  end

  def update
    @cat_parent = CatParent.find(params[:id])
    @cat_parent.name = params.dig(:cat_parent, :name)
    if @cat_parent.save
      redirect_to cat_parent_path(@cat_parent), notice: '保存しました'
    else
      render :edit
    end
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  around_action :with_readonly_another, except: []

  def index
  end

end

app/controllers/dog_children_controller.rb
class DogChildrenController < ApplicationController
  # メソッド指定で除外できるが、遅延発生時にデータ不整合が起きたように見えるので非推奨。書き込みがあるコントローラではreadonlyにしないほうがいよい
  around_action :with_readonly, except: [:child_create, :child_update]

  def children
    @dog_parent = DogParent.find(params[:id])
    @dog_children = @dog_parent.dog_children
  end

  def child_show
    @dog_child = DogChild.find(params[:id])
  end

  def child_new
    @dog_parent = DogParent.find(params[:id])
    @dog_child = DogChild.new
  end

  def child_create
    @dog_parent = DogParent.find(params[:id])
    @dog_child = @dog_parent.dog_children.build
    @dog_child.name = params.dig(:dog_child, :name)
    if @dog_child.save
      redirect_to children_dog_child_path(@dog_parent), notice: '作成しました'
    else
      render :child_new
    end
  end

  def child_show
    @dog_child = DogChild.find(params[:id])
  end

  def child_edit
    @dog_child = DogChild.find(params[:id])
  end

  def child_update
    @dog_child = DogChild.find(params[:id])
    @dog_child.name = params.dig(:dog_child, :name)
    if @dog_child.save
      redirect_to child_show_dog_child_path(@dog_child), notice: '保存しました'
    else
      render :child_edit
    end
  end
end

app/controllers/dog_parents_controller.rb
class DogParentsController < ApplicationController

  def index
  end

  def show
  end

  def new
    @dog_parent = DogParent.new
  end

  def create
    @dog_parent = DogParent.new
    @dog_parent.name = params.dig(:dog_parent, :name)
    if @dog_parent.save
      redirect_to dog_parents_path, notice: '作成しました'
    else
      render :new
    end
  end

  def show
    @dog_parent = DogParent.find(params[:id])
  end

  def edit
    @dog_parent = DogParent.find(params[:id])
  end

  def update
    @dog_parent = DogParent.find(params[:id])
    @dog_parent.name = params.dig(:dog_parent, :name)
    if @dog_parent.save
      redirect_to dog_parent_path(@dog_parent), notice: '保存しました'
    else
      render :edit
    end
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  around_action :with_readonly, except: []

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    redirect_to animals_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/index.html.slim
= render partial: "global/bread"

h2
  | 犬
p
  
  a[href="#{dogs_path}"]
    | 親犬の数 #{@dog_parents_count}、
    / -> readonly : controllerでwith_readonlyを指定しているからread側

    | 子犬の数 #{DogChild.all.size}
    / -> writable : viewではデフォルトのwrite側


h2
  | 猫
p
  a[href="#{cats_path}"]
    | 親猫の数 #{@cat_parents.all.size}、
    / -> writable : controllerでwith_readonlyを指定しているが、viewでsizeを付与し、実行タイミングがブロックから外れるためwriter側

    | 子猫の数 #{CatChild.all.size}
    / -> writable : viewではデフォルトのwrite側

app/views/cat_children/child_edit.html.slim
= render partial: "global/bread", locals: { second_title: '猫の情報', second_url: "#{cats_path}", third_title: '親の一覧', third_url: "#{cat_parents_path}", fourth_title: '親の詳細', fourth_url: "#{cat_parent_path(@cat_child.cat_parent)}", fifth_title: '子供一覧', fifth_url: "#{children_cat_child_path(@cat_child.cat_parent)}", sixth_title: '子の詳細'  }

h1
  | #{@cat_child.name}の編集

- @cat_child.errors.full_messages.first if @cat_child.errors.any?
= form_for(@cat_child, url: child_update_cat_child_path(@cat_child), method: :patch ) do |f|
    = f.text_field :name, { class: '', placeholder: '例) ミケ' }
    = submit_tag("送信", class: '', data: {disable_with: '送信中'})

app/views/cat_children/child_new.html.slim
= render partial: "global/bread", locals: { second_title: '猫の情報', second_url: "#{cats_path}", third_title: '親の一覧', third_url: "#{cat_parents_path}", fourth_title: '親の詳細', fourth_url: "#{cat_parent_path(@cat_parent)}", fifth_title: '子供一覧', fifth_url: "#{children_cat_child_path(@cat_parent)}", sixth_title: '新規作成'  }

h1
  | #{@cat_parent.name}の子供の新規作成

- @cat_child.errors.full_messages.first if @cat_child.errors.any?
= form_for(@cat_child, url: child_create_cat_child_path(@cat_parent), method: :post ) do |f|
  = f.text_field :name, { class: '', placeholder: '例) ミケ' }
  = submit_tag("送信", class: '', data: {disable_with: '送信中'})

app/views/cat_children/child_show.html.slim
= render partial: "global/bread", locals: { second_title: '猫の情報', second_url: "#{cats_path}", third_title: '親の一覧', third_url: "#{cat_parents_path}", fourth_title: '親の詳細', fourth_url: "#{cat_parent_path(@cat_child.cat_parent)}", fifth_title: '子供一覧', fifth_url: "#{children_cat_child_path(@cat_child.cat_parent)}", sixth_title: '子の詳細'  }

h1
  | #{@cat_child.name}の詳細
p
  | 名前 #{@cat_child.name} (
  a[href="#{child_edit_cat_child_path(@cat_child)}"]
    | 編集する
  | )
p
  | 親の名前 #{@cat_child.cat_parent.name}

app/views/cat_children/children.html.slim
= render partial: "global/bread", locals: { second_title: '猫の情報', second_url: "#{cats_path}", third_title: '親の一覧', third_url: "#{cat_parents_path}", fourth_title: '親の詳細', fourth_url: "#{cat_parent_path(@cat_parent)}", fifth_title: '子供一覧'  }

h1
  | #{@cat_parent.name}の子供一覧

ul
  - @cat_children.all.each do |cat_child|
    li
      a[href="#{child_show_cat_child_path(cat_child)}"]
        = cat_child.name

hr
a[href="#{child_new_cat_child_path(@cat_parent)}"]
  | 新規作成

app/views/cat_parents/edit.html.slim
= render partial: "global/bread", locals: { second_title: '猫の情報', second_url: "#{cats_path}", third_title: '猫の一覧', third_url: "#{cat_parents_path}", fourth_title: '親の編集' }

h1
  | 親の編集

- @cat_parent.errors.full_messages.first if @cat_parent.errors.any?
= form_for(@cat_parent, url: cat_parent_path(@cat_parent), method: :patch ) do |f|
    = f.text_field :name, { class: '', placeholder: '例) ポチ' }
    = submit_tag("送信", class: '', data: {disable_with: '送信中'})

app/views/cat_parents/index.html.slim
= render partial: "global/bread", locals: { second_title: '猫の情報', second_url: "#{cats_path}", third_title: '猫の一覧' }

h1
  | 親の一覧

ul
  - CatParent.all.each do |cat_parent|
    li
      a[href="#{cat_parent_path(cat_parent)}"]
        | #{cat_parent.name}

hr
a[href="#{new_cat_parent_path}"]
  | 新規作成

app/views/cat_parents/new.html.slim
= render partial: "global/bread", locals: { second_title: '猫の情報', second_url: "#{cats_path}", third_title: '親の一覧', third_url: "#{cat_parents_path}", fourth_title: '新規作成' }

h1
  | 親の新規作成

- @cat_parent.errors.full_messages.first if @cat_parent.errors.any?
= form_for(@cat_parent, url: cat_parents_path, method: :post ) do |f|
  = f.text_field :name, { class: '', placeholder: '例) タマ' }
  = submit_tag("送信", class: '', data: {disable_with: '送信中'})

app/views/cat_parents/show.html.slim
= render partial: "global/bread", locals: { second_title: '猫の情報', second_url: "#{cats_path}", third_title: '親の一覧', third_url: "#{cat_parents_path}", fourth_title: '親の詳細' }

h1
  | 親の詳細
p
  | 名前 #{@cat_parent.name} (
  a[href="#{edit_cat_parent_path(@cat_parent)}"]
    | 編集する
  | )
p
  | 子供の数 #{@cat_parent.cat_children.size} (
  a[href="#{children_cat_child_path(@cat_parent)}"]
    | 子供の情報を見る
  | )

app/views/cats/index.html.slim
= render partial: "global/bread", locals: { second_title: '猫の情報' }

h2
  | 猫の情報
p
  | 親の数 #{CatParent.all.size}
  br
  | 子供の数 #{CatChild.all.size}

a[href="#{cat_parents_path}"]
  | 詳細を見る

app/views/dog_children/child_edit.html.slim
= render partial: "global/bread", locals: { second_title: '犬の情報', second_url: "#{dogs_path}", third_title: '親の一覧', third_url: "#{dog_parents_path}", fourth_title: '親の詳細', fourth_url: "#{dog_parent_path(@dog_child.dog_parent)}", fifth_title: '子供一覧', fifth_url: "#{children_dog_child_path(@dog_child.dog_parent)}", sixth_title: '子の詳細'  }

h1
  | #{@dog_child.name}の編集

- @dog_child.errors.full_messages.first if @dog_child.errors.any?
= form_for(@dog_child, url: child_update_dog_child_path(@dog_child), method: :patch ) do |f|
    = f.text_field :name, { class: '', placeholder: '例) コロ' }
    = submit_tag("送信", class: '', data: {disable_with: '送信中'})

app/views/dog_children/child_new.html.slim
= render partial: "global/bread", locals: { second_title: '犬の情報', second_url: "#{dogs_path}", third_title: '親の一覧', third_url: "#{dog_parents_path}", fourth_title: '親の詳細', fourth_url: "#{dog_parent_path(@dog_parent)}", fifth_title: '子供一覧', fifth_url: "#{children_dog_child_path(@dog_parent)}", sixth_title: '新規作成'  }

h1
  | #{@dog_parent.name}の子供の新規作成

- @dog_child.errors.full_messages.first if @dog_child.errors.any?
= form_for(@dog_child, url: child_create_dog_child_path(@dog_parent), method: :post ) do |f|
  = f.text_field :name, { class: '', placeholder: '例) コロ' }
  = submit_tag("送信", class: '', data: {disable_with: '送信中'})

app/views/dog_children/child_show.html.slim
= render partial: "global/bread", locals: { second_title: '犬の情報', second_url: "#{dogs_path}", third_title: '親の一覧', third_url: "#{dog_parents_path}", fourth_title: '親の詳細', fourth_url: "#{dog_parent_path(@dog_child.dog_parent)}", fifth_title: '子供一覧', fifth_url: "#{children_dog_child_path(@dog_child.dog_parent)}", sixth_title: '子の詳細'  }

h1
  | #{@dog_child.name}の詳細
p
  | 名前 #{@dog_child.name} (
  a[href="#{child_edit_dog_child_path(@dog_child)}"]
    | 編集する
  | )
p
  | 親の名前 #{@dog_child.dog_parent.name}

app/views/dog_children/children.html.slim
= render partial: "global/bread", locals: { second_title: '犬の情報', second_url: "#{dogs_path}", third_title: '親の一覧', third_url: "#{dog_parents_path}", fourth_title: '親の詳細', fourth_url: "#{dog_parent_path(@dog_parent)}", fifth_title: '子供一覧'  }

h1
  | #{@dog_parent.name}の子供一覧

ul
  - @dog_children.all.each do |dog_child|
    li
      a[href="#{child_show_dog_child_path(dog_child)}"]
        = dog_child.name

hr
a[href="#{child_new_dog_child_path(@dog_parent)}"]
  | 新規作成

app/views/dog_parents/edit.html.slim
= render partial: "global/bread", locals: { second_title: '犬の情報', second_url: "#{dogs_path}", third_title: '親の一覧', third_url: "#{dog_parents_path}", fourth_title: '親の編集' }

h1
  | 親の編集

- @dog_parent.errors.full_messages.first if @dog_parent.errors.any?
= form_for(@dog_parent, url: dog_parent_path(@dog_parent), method: :patch ) do |f|
    = f.text_field :name, { class: '', placeholder: '例) ポチ' }
    = submit_tag("送信", class: '', data: {disable_with: '送信中'})

app/views/dog_parents/index.html.slim
= render partial: "global/bread", locals: { second_title: '犬の情報', second_url: "#{dogs_path}", third_title: '親の一覧' }

h1
  | 親の一覧

ul
  - DogParent.all.each do |dog_parent|
    li
      a[href="#{dog_parent_path(dog_parent)}"]
        | #{dog_parent.name}

hr
a[href="#{new_dog_parent_path}"]
  | 新規作成

app/views/dog_parents/new.html.slim
= render partial: "global/bread", locals: { second_title: '犬の情報', second_url: "#{dogs_path}", third_title: '親の一覧', third_url: "#{dog_parents_path}", fourth_title: '新規作成' }

h1
  | 親の新規作成

- @dog_parent.errors.full_messages.first if @dog_parent.errors.any?
= form_for(@dog_parent, url: dog_parents_path, method: :post ) do |f|
  = f.text_field :name, { class: '', placeholder: '例) ポチ' }
  = submit_tag("送信", class: '', data: {disable_with: '送信中'})

app/views/dog_parents/show.html.slim
= render partial: "global/bread", locals: { second_title: '犬の情報', second_url: "#{dogs_path}", third_title: '親の一覧', third_url: "#{dog_parents_path}", fourth_title: '親の詳細' }

h1
  | 親の詳細
p
  | 名前 #{@dog_parent.name} (
  a[href="#{edit_dog_parent_path(@dog_parent)}"]
    | 編集する
  | )
p
  | 子供の数 #{@dog_parent.dog_children.size} (
  a[href="#{children_dog_child_path(@dog_parent)}"]
    | 子供の情報を見る
  | )

app/views/dogs/index.html.slim
= render partial: "global/bread", locals: { second_title: '犬の情報' }

h2
  | 犬の情報
p
  | 親の数 #{DogParent.all.size}
  / -> readonly: Controllerのaroundで指定した場合は、viewもその影響を受ける
  br
  | 子供の数 #{DogChild.all.size}
  / -> readonly: Controllerのaroundで指定した場合は、viewもその影響を受ける

a[href="#{dog_parents_path}"]
  | 詳細を見る

app/views/global/_bread.html.slim
- second_title = second_title
- second_url   = second_url
- third_title  = third_title
- third_url    = third_url
- fourth_title = fourth_title
- fourth_url   = fourth_url
- fifth_title  = fifth_title
- fifth_url    = fifth_url
- sixth_title  = sixth_title
- sixth_url    = sixth_url

.mock-bread
  ul
    li
      a[href="#{animals_path}"]
        | TOP
    - if second_title.present?
      li
        - if second_url.present?
          a[href="#{second_url}"]
            = second_title
        - else
          = second_title

    - if third_title.present?
      li
        - if third_url.present?
          a[href="#{third_url}"]
            = third_title
        - else
          = third_title

    - if fourth_title.present?
      li
        - if fourth_url.present?
          a[href="#{fourth_url}"]
            = fourth_title
        - else
          = fourth_title

    - if fifth_title.present?
      li
        - if fifth_url.present?
          a[href="#{fifth_url}"]
            = fifth_title
        - else
          = fifth_title

    - if sixth_title.present?
      li
        - if sixth_url.present?
          a[href="#{sixth_url}"]
            = sixth_title
        - else
          = sixth_title

app/views/layouts/application.html.slim
doctype html
html
  head
    / title
    title
      | Switchpoint Structure

    / tags
    = csrf_meta_tags
    meta[content="text/html;charset=utf-8" http-equiv="Content-Type"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"]
    meta[name="robots" content="noindex"]

    / css
    = stylesheet_link_tag "application", media: "all"

    / js head
    = javascript_include_tag 'application'

  body
    .mock-layout.container
      = yield